# Configuration for Brain-Inspired Neural Network Stock Prediction

general:
  seed: 42
  device: "cuda"  # or "cpu"
  log_dir: "logs/stock_prediction/"
  checkpoint_dir: "checkpoints/stock_prediction/"
  results_dir: "results/stock_prediction/"

data:
  # Stock selection
  ticker_symbol: "AAPL"
  start_date: "2018-01-01"
  end_date: "2023-01-01"
  
  # Sequence modeling parameters
  sequence_length: 60  # 60 days of price history
  prediction_horizon: 5  # Predict 5 days ahead
  target_column: "Close"
  feature_columns: ["Open", "High", "Low", "Close", "Volume", "Adj Close"]
  
  # Technical indicators (automatically calculated)
  use_technical_indicators: true
  ma_windows: [5, 10, 20, 50]
  rsi_window: 14
  bb_window: 20
  bb_std_dev: 2
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  
  # Dataset split
  train_ratio: 0.7
  val_ratio: 0.15  # Remaining 0.15 for test

# Parameters must match the structure expected by BrainInspiredNN
controller:
  hidden_size: 256  # Match original config 
  persistent_memory_size: 128  # Match original config
  num_layers: 2
  dropout: 0.2  # Slightly higher for financial data

neuromodulator:
  # Enhanced neuromodulation for financial market dynamics
  dopamine_scale: 1.2  # Increased for reward prediction in markets
  serotonin_scale: 0.8  # Balanced risk assessment
  norepinephrine_scale: 1.0  # Enhanced attention to volatility
  acetylcholine_scale: 0.9  # Enhanced memory formation
  reward_decay: 0.97  # Slightly higher than default for longer memory

training:
  batch_size: 32
  learning_rate: 0.0005  # Lower learning rate for stability
  num_epochs: 150
  optimizer: "adam"
  scheduler: "cosine"
  early_stopping: true
  patience: 20