# Brain-Inspired Neural Network Configuration

# General parameters
general:
  device: "cpu"  # Default to CPU for testing
  results_dir: "/home/ubuntu/results"
  
# Model parameters
model:
  input_size: 64  # Match the checkpoint model
  hidden_size: 128
  output_size: 32  # Match the checkpoint model
  
# Controller parameters
controller:
  type: "persistent_gru"
  num_layers: 2
  persistent_memory_size: 64
  dropout: 0.2
  
# Neuromodulator parameters
neuromodulator:
  dopamine_scale: 1.0
  serotonin_scale: 1.0
  norepinephrine_scale: 1.0
  acetylcholine_scale: 1.0
  reward_decay: 0.95
  
# Training parameters
training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 100
  optimizer: "adam"
  
# Data parameters
data:
  dataset: "financial"
  ticker_symbol: "AAPL"
  test_ticker: "AAPL"
  features: ["Open", "High", "Low", "Close", "Volume"]
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  sequence_length: 50
  prediction_horizon: 1
  normalize: true
