# Update the config file for financial timeseries prediction

# General parameters
general:
  device: "cuda"  # Use GPU if available
  results_dir: "results"
  
# Model parameters
model:
  input_size: 25  # Will be automatically adjusted based on data features
  hidden_size: 128
  output_size: 1  # Predicting a single value (next price)
  use_bio_gru: true  # Use the biologically-inspired GRU
  
# Controller parameters
controller:
  type: "persistent_gru"
  num_layers: 2
  persistent_memory_size: 64
  dropout: 0.2
  
# Neuromodulator parameters
neuromodulator:
  dopamine_scale: 1.0
  serotonin_scale: 0.8
  norepinephrine_scale: 0.7
  acetylcholine_scale: 0.9
  reward_decay: 0.95
  
# Pretraining parameters (NEW)
pretraining:
  enabled: true
  epochs: 5
  controller:
    enabled: true
    learning_rate: 0.001
  neuromodulator:
    enabled: true
    learning_rate: 0.0005
  
# Training parameters
training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 100
  weight_decay: 0.0001
  learning_mode: "neuromodulator"  # Use neuromodulator-driven learning
  optimizer: "adam"
  early_stopping_patience: 30
  accuracy_threshold: 0.02  # 2% price prediction accuracy threshold
  
# Data parameters
data:
  dataset: "financial"
  ticker_symbol: "AAPL"  # Stock symbol to predict
  features: "all"  # Use all available features and indicators
  start_date: "2018-01-01"  # Start date for data
  end_date: "2023-12-31"  # End date for data
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  sequence_length: 40  # Use 40 days of history to predict the next day
  prediction_horizon: 1  # Predict 1 day into the future
  target_column: "Close"  # Target column to predict
  normalize: "standard"  # Use standard normalization
  include_indicators: true  # Include technical indicators
  num_workers: 2  # DataLoader workers
  pin_memory: true  # Pin memory for faster data transfer to GPU

# Neuron optimization parameters
neuron_optimization:
  enabled: true
  target_activity: 0.15
  homeostatic_rate: 0.01
  health_decay: 0.99
  death_threshold: 0.1
  plasticity:
    hebbian_weight: 0.3
    error_weight: 0.7
    regularization: 0.0001
  synapse:
    facilitation_rate: 0.1
    depression_rate: 0.2
    normalization: "l2"

  # Enhanced preprocessing
  use_advanced_features: true
  regime_aware_training: false
  ensemble_augmentation: false
  n_ensembles: 3
  
  # Augmentation parameters
  augment_prob: 0.5
  augment_strength: 0.05
  
  # Cross-validation
  cv_folds: 5
  cv_test_size: 0.2

  # General parameters
general:
  device: "cuda"  # Use GPU if available
  results_dir: "results"
  
# Model parameters
model:
  input_size: 5  # Will be automatically adjusted based on data features
  hidden_size: 256
  output_size: 1  # Predicting a single value (next price)
  use_bio_gru: true  # Use the biologically-inspired GRU
  
# Controller parameters
controller:
  type: "persistent_gru"
  num_layers: 2
  persistent_memory_size: 128
  dropout: 0.2
  
# Neuromodulator parameters
neuromodulator:
  dopamine_scale: 1.0
  serotonin_scale: 0.8
  norepinephrine_scale: 0.7
  acetylcholine_scale: 0.9
  reward_decay: 0.95
  
# Pretraining parameters
pretraining:
  enabled: true
  epochs: 5
  controller:
    enabled: true
    learning_rate: 0.001
  neuromodulator:
    enabled: true
    learning_rate: 0.0005
  
# Training parameters
training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 100
  weight_decay: 0.0001
  learning_mode: "neuromodulator"  # Use neuromodulator-driven learning
  optimizer: "adam"
  early_stopping_patience: 30
  accuracy_threshold: 0.02  # 2% price prediction accuracy threshold
  gradient_clip: 1.0
  
# Data parameters
data:
  dataset: "financial"
  ticker_symbol: "AAPL"  # Stock symbol to predict
  features: ["Open", "High", "Low", "Close", "Volume"]  # Changed from "all" to explicit list
  start_date: "2020-01-01"  # Start date for data
  end_date: "2023-12-31"  # End date for data
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  sequence_length: 30  # Reduced from 40 to 30 for better compatibility
  prediction_horizon: 1  # Predict 1 day into the future
  target_column: "Close"  # Target column to predict
  normalize: true  # Use normalization
  include_indicators: false  # Disabled for now to avoid complexity
  train_samples: 1000  # Explicit number of training samples
  val_samples: 200     # Explicit number of validation samples
  num_workers: 0  # Set to 0 to avoid multiprocessing issues
  pin_memory: false

